### ISSUE TITLE
Suggested reorganization of UNF site

### ISSUE THREAD

**Issue by julieaboyle1** [UNFmontreal/unf-montreal.ca#10]
@arnaudbore I did what you asked me to and I thought a bit outside the box, to see if we can come up with more updated version of our site. I have not removed any essential info (or not on purpose at least). 

As usual just an outline to work from... @cyrand wanna look it over and @bpinsard if you have time. Given it's length, I did nit post as individual issues but rather a google doc we can comment on :

https://docs.google.com/document/d/1TTWk493KT9iA_yT0mE2B9DypEb1nc4BSX4ecG2sqdHY/edit?usp=sharing

**Comment by arnaudbore** [comment]
Done !
