### ISSUE TITLE
Add slack invitation link

### ISSUE THREAD

**Issue by jcohenadad** [UNFmontreal/unf-montreal.ca#58]
suggestion: add this link "https://join.slack.com/t/mic-unf/shared_invite/zt-vfzkoaoz-5azUSSY7LASx09vj7Aw5kg"

on this page: https://unf-montreal.ca/contact/

That's probably the page to butcher: https://github.com/UNFmontreal/unf-montreal.ca/blob/master/layouts/contact/list.html

and if we'd like to do things properly we should probably not hard-code the slack invitation link there... but i'm not an html expert so i'm not going to work on that one

**Comment by julieaboyle1** [comment]
HI Julien, as it stand any person with an email addresses from UdeM, Poly, CRIUGM, Concordia, UQTR can be added by any member and approved by admins. Otherwise they need to be added by one of the admins of UNF slack (or so is my understanding from the settings and permission section of our account.

**Comment by jcohenadad** [comment]
right-- the idea was just to add an invit link on the website because currently, new ppl are not aware _how_ they can be added to the slack-- so new members joining can be told to "go on UNF "onboarding page", and that onboarding page would list all the things they need to do in order to be fully operational with UNF.  A bit like what we are trying to do [here](https://intranet.neuro.polymtl.ca/onboarding)

for example, my student was told by email she should join slack, then the student wrote back she didn't know how to, then i chipped in and answered, and then i added that person manually on slack-- it's a cumulative 5min time for 3 people, vs. 1 min time for 1 person if it was advertised on the website.

**Comment by arnaudbore** [comment]
Added
