### ISSUE TITLE
Website does not render well in phone

### ISSUE THREAD

**Issue by jcohenadad** [UNFmontreal/unf-montreal.ca#64]
Menu selection not possible on my iPhone:

![C1C151D1-392F-4C12-AA29-751E9E34C5CD](https://user-images.githubusercontent.com/2482071/169651492-dc7666c2-bf78-4c0c-818c-1aa462c28611.png)

**Comment by arnaudbore** [comment]
Just added a white background to highlight the menu for the mobile version of the website.
